// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function ConvertQuotationToInvoice(arg1) {
  return window['go']['main']['App']['ConvertQuotationToInvoice'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreateQuotation(arg1) {
  return window['go']['main']['App']['CreateQuotation'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function ExportMasterReport() {
  return window['go']['main']['App']['ExportMasterReport']();
}

export function ExportSalesExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportSalesExcel'](arg1, arg2);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetDashboardStats(arg1, arg2) {
  return window['go']['main']['App']['GetDashboardStats'](arg1, arg2);
}

export function GetEmisorConfig() {
  return window['go']['main']['App']['GetEmisorConfig']();
}

export function GetFacturasPaginated(arg1, arg2) {
  return window['go']['main']['App']['GetFacturasPaginated'](arg1, arg2);
}

export function GetMailLogs() {
  return window['go']['main']['App']['GetMailLogs']();
}

export function GetNextQuotationSecuencial() {
  return window['go']['main']['App']['GetNextQuotationSecuencial']();
}

export function GetNextSecuencial() {
  return window['go']['main']['App']['GetNextSecuencial']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetQuotations(arg1, arg2) {
  return window['go']['main']['App']['GetQuotations'](arg1, arg2);
}

export function GetSatelliteConnectionInfo() {
  return window['go']['main']['App']['GetSatelliteConnectionInfo']();
}

export function GetStatisticsCharts() {
  return window['go']['main']['App']['GetStatisticsCharts']();
}

export function GetSyncLogs() {
  return window['go']['main']['App']['GetSyncLogs']();
}

export function GetTopProducts() {
  return window['go']['main']['App']['GetTopProducts']();
}

export function GetVATSummary(arg1, arg2) {
  return window['go']['main']['App']['GetVATSummary'](arg1, arg2);
}

export function ImportClientsCSV() {
  return window['go']['main']['App']['ImportClientsCSV']();
}

export function ImportProductsCSV() {
  return window['go']['main']['App']['ImportProductsCSV']();
}

export function NotifyFrontend(arg1, arg2) {
  return window['go']['main']['App']['NotifyFrontend'](arg1, arg2);
}

export function OpenFacturaPDF(arg1) {
  return window['go']['main']['App']['OpenFacturaPDF'](arg1);
}

export function OpenInvoiceFolder(arg1) {
  return window['go']['main']['App']['OpenInvoiceFolder'](arg1);
}

export function OpenInvoiceXML(arg1) {
  return window['go']['main']['App']['OpenInvoiceXML'](arg1);
}

export function OpenQuotationPDF(arg1) {
  return window['go']['main']['App']['OpenQuotationPDF'](arg1);
}

export function ResendInvoiceEmail(arg1) {
  return window['go']['main']['App']['ResendInvoiceEmail'](arg1);
}

export function SaveClient(arg1) {
  return window['go']['main']['App']['SaveClient'](arg1);
}

export function SaveEmisorConfig(arg1) {
  return window['go']['main']['App']['SaveEmisorConfig'](arg1);
}

export function SaveProduct(arg1) {
  return window['go']['main']['App']['SaveProduct'](arg1);
}

export function SearchClients(arg1) {
  return window['go']['main']['App']['SearchClients'](arg1);
}

export function SearchInvoicesSmart(arg1) {
  return window['go']['main']['App']['SearchInvoicesSmart'](arg1);
}

export function SearchProducts(arg1) {
  return window['go']['main']['App']['SearchProducts'](arg1);
}

export function SelectAndSaveLogo() {
  return window['go']['main']['App']['SelectAndSaveLogo']();
}

export function SelectBackupPath() {
  return window['go']['main']['App']['SelectBackupPath']();
}

export function SelectCertificate() {
  return window['go']['main']['App']['SelectCertificate']();
}

export function SelectStoragePath() {
  return window['go']['main']['App']['SelectStoragePath']();
}

export function TestSMTPConnection(arg1) {
  return window['go']['main']['App']['TestSMTPConnection'](arg1);
}

export function TriggerSyncManual() {
  return window['go']['main']['App']['TriggerSyncManual']();
}
