// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';
import {service} from '../models';

export function ActivateLicense(arg1:string):Promise<string>;

export function CheckLicense():Promise<boolean>;

export function ConvertQuotationToInvoice(arg1:number):Promise<db.FacturaDTO>;

export function CreateBackup():Promise<void>;

export function CreateInvoice(arg1:db.FacturaDTO):Promise<string>;

export function CreateQuotation(arg1:db.QuotationDTO):Promise<string>;

export function DeleteClient(arg1:string):Promise<string>;

export function DeleteProduct(arg1:string):Promise<string>;

export function ExportMasterReport():Promise<string>;

export function ExportSalesExcel(arg1:string,arg2:string):Promise<string>;

export function GetBackups():Promise<Array<main.BackupDTO>>;

export function GetClients():Promise<Array<db.ClientDTO>>;

export function GetDashboardStats(arg1:string,arg2:string):Promise<main.DashboardStats>;

export function GetEmisorConfig():Promise<db.EmisorConfigDTO>;

export function GetFacturasPaginated(arg1:number,arg2:number):Promise<main.FacturasResponse>;

export function GetMailLogs():Promise<Array<db.MailLogDTO>>;

export function GetNextQuotationSecuencial():Promise<string>;

export function GetNextSecuencial():Promise<string>;

export function GetProducts():Promise<Array<db.ProductDTO>>;

export function GetQuotations(arg1:number,arg2:number):Promise<main.QuotationListResponse>;

export function GetStatisticsCharts():Promise<main.ChartsDTO>;

export function GetSyncLogs():Promise<Array<service.SyncLog>>;

export function GetTopProducts():Promise<Array<service.TopProduct>>;

export function GetVATSummary(arg1:string,arg2:string):Promise<service.TaxSummary>;

export function ImportClientsCSV():Promise<string>;

export function ImportProductsCSV():Promise<string>;

export function NotifyFrontend(arg1:string,arg2:string):Promise<void>;

export function OpenFacturaPDF(arg1:string):Promise<string>;

export function OpenInvoiceFolder(arg1:string):Promise<string>;

export function OpenInvoiceXML(arg1:string):Promise<string>;

export function OpenQuotationPDF(arg1:number):Promise<string>;

export function ResendInvoiceEmail(arg1:string):Promise<string>;

export function SaveClient(arg1:db.ClientDTO):Promise<string>;

export function SaveEmisorConfig(arg1:db.EmisorConfigDTO):Promise<string>;

export function SaveProduct(arg1:db.ProductDTO):Promise<string>;

export function SearchClients(arg1:string):Promise<Array<db.ClientDTO>>;

export function SearchInvoicesSmart(arg1:string):Promise<Array<db.FacturaResumenDTO>>;

export function SearchProducts(arg1:string):Promise<Array<db.ProductDTO>>;

export function SelectAndSaveLogo():Promise<string>;

export function SelectBackupPath():Promise<string>;

export function SelectCertificate():Promise<string>;

export function SelectStoragePath():Promise<string>;

export function TestSMTPConnection(arg1:db.EmisorConfigDTO):Promise<string>;

export function TriggerSyncManual():Promise<string>;
